CREATE TABLE nombres (_id INTEGER PRIMARY KEY, nombre TEXT, origen TEXT, descripcion TEXT);
INSERT INTO nombres VALUES(1,'aaron','Hebreo','Elevado, alto, montañoso');
INSERT INTO nombres VALUES(2,'abel','Hebreo','Aliento, respiración,vanidad');
INSERT INTO nombres VALUES(3,'abelardo','Germano','Noble, Osado, temerario');
INSERT INTO nombres VALUES(4,'abigaíl','Hebreo','Fuente de alegría');
INSERT INTO nombres VALUES(5,'abraham','Hebreo','Padre superior');
INSERT INTO nombres VALUES(6,'abril','Latino','Apertura');
INSERT INTO nombres VALUES(7,'ada','Hebreo','Belleza');
INSERT INTO nombres VALUES(8,'adalberto','Germano','Que brilla noblemente');
INSERT INTO nombres VALUES(9,'adán','Hebreo','Hombre de la tierra');
INSERT INTO nombres VALUES(10,'adela','Germano','De noble cuna');
INSERT INTO nombres VALUES(11,'adelaida','Germano','De noble cuna');
INSERT INTO nombres VALUES(12,'adelina','Germano','De noble cuna');
INSERT INTO nombres VALUES(13,'adelmo','Germano','Noble');
INSERT INTO nombres VALUES(14,'adolfo','Germano','Lobo, noble');
INSERT INTO nombres VALUES(15,'adrián','Latino','De Adria (Del Mar Adriático)');
INSERT INTO nombres VALUES(16,'adriano','Latino','Negro');
INSERT INTO nombres VALUES(17,'ágata','Griego','Buena, amable');
INSERT INTO nombres VALUES(18,'águeda','Griego','Buena, amable');
INSERT INTO nombres VALUES(19,'agustín','Latino','Perteneciente a Agosto');
INSERT INTO nombres VALUES(20,'aída','Italiano','Conductora');
INSERT INTO nombres VALUES(21,'ainara','Vasco','Originario de Vizcaya. Sin datos');
INSERT INTO nombres VALUES(22,'alan','Germano','De la tribu de los Alanos');
INSERT INTO nombres VALUES(23,'albano','Latino','Blanco, puro, luminoso');
INSERT INTO nombres VALUES(24,'alberto','Germano','Que brilla con nobleza');
INSERT INTO nombres VALUES(25,'alcira','Árabe','Natural de Algeciras (España)');
INSERT INTO nombres VALUES(26,'aldo','Germano','Experto');
INSERT INTO nombres VALUES(27,'alejandro alejandra','Griego','Protector de los hombres');
INSERT INTO nombres VALUES(28,'alejo','Germano','Arroja el mal');
INSERT INTO nombres VALUES(29,'alfonso','Germano','Estratega');
INSERT INTO nombres VALUES(30,'alfredo','Germano','Consejero');
INSERT INTO nombres VALUES(31,'alicia','Germano','Noble alegría, consuelo');
INSERT INTO nombres VALUES(32,'alina','Germano','Amiga noble');
INSERT INTO nombres VALUES(33,'almudena','Árabe','La ciudad');
INSERT INTO nombres VALUES(34,'alonso','Germano','Estratega (Variante de Alfonso)');
INSERT INTO nombres VALUES(35,'álvaro','Germano','Atento');
INSERT INTO nombres VALUES(36,'amadeo','Latino','Que ama a Dios');
INSERT INTO nombres VALUES(37,'amalia','Germano','Laboriosa');
INSERT INTO nombres VALUES(38,'amancio','Latino','Amante');
INSERT INTO nombres VALUES(39,'amanda','Latino','Merecedora de amor');
INSERT INTO nombres VALUES(40,'amaranto','Griego','Flor eterna');
INSERT INTO nombres VALUES(41,'amaya','Vasco','Principio del fin');
INSERT INTO nombres VALUES(42,'amos','Hebreo','Carga');
INSERT INTO nombres VALUES(43,'ambrosio','Griego','Inmortal, Divino');
INSERT INTO nombres VALUES(44,'amelia','Germano','Afanosa, enérgica');
INSERT INTO nombres VALUES(45,'amira','Árabe','La princesa');
INSERT INTO nombres VALUES(46,'amparo','Latino','Protectora');
INSERT INTO nombres VALUES(47,'ana','Hebreo','Graciosa');
INSERT INTO nombres VALUES(48,'anacleto','Griego','Que invoca auxilio');
INSERT INTO nombres VALUES(49,'anastasia','Griego','Resucitado, resurrección');
INSERT INTO nombres VALUES(50,'ander','Vasco','Forma vasca de Andrés (del griego andros: Hombre)');
INSERT INTO nombres VALUES(51,'andrés','Griego','Viril');
INSERT INTO nombres VALUES(52,'ángel ángela','Griego','Mensajero, angelical');
INSERT INTO nombres VALUES(53,'angelina angélica','Griego','Mensajero, angelical');
INSERT INTO nombres VALUES(54,'ángeles','Griego','Buena, pura, mensajera celeste');
INSERT INTO nombres VALUES(55,'aníbal','Fenicio','Gracia de Baal (El Dios)');
INSERT INTO nombres VALUES(56,'aniceto','Griego','Invicto');
INSERT INTO nombres VALUES(57,'angustias','Latino','Angosto, difícil');
INSERT INTO nombres VALUES(58,'anselmo','Germano','Guerrero del Señor');
INSERT INTO nombres VALUES(59,'antonio','Latino','Digno de alabanza');
INSERT INTO nombres VALUES(60,'antonia','Latino','Digno de alabanza');
INSERT INTO nombres VALUES(61,'antonieta','Latino','Florcita, llena de gracia');
INSERT INTO nombres VALUES(62,'apolo','Griego','Dios del sol');
INSERT INTO nombres VALUES(63,'aquiles','Griego','Consuelo en el dolor');
INSERT INTO nombres VALUES(64,'aquilino','Latino','Como el águila');
INSERT INTO nombres VALUES(65,'araceli','Latino','Altar del cielo');
INSERT INTO nombres VALUES(66,'archibaldo','Germano','Muy valiente');
INSERT INTO nombres VALUES(67,'ariadna','Griego','De dulce canto');
INSERT INTO nombres VALUES(68,'ariel','Hebreo','León de Dios');
INSERT INTO nombres VALUES(69,'arístides','Griego','Hijo del mejor');
INSERT INTO nombres VALUES(70,'armando','Germano','Conductor de huestes');
INSERT INTO nombres VALUES(71,'arnoldo','Germano','Fuerte como un águila');
INSERT INTO nombres VALUES(72,'arturo','Celta','Alto, noble.Centinela de la osa mayor');
INSERT INTO nombres VALUES(73,'asunción','Latino','Elevación');
INSERT INTO nombres VALUES(74,'atanasio','Griego','Inmortal');
INSERT INTO nombres VALUES(75,'augusto','Latino','Imperial');
INSERT INTO nombres VALUES(76,'aurelio','Latino','Dorado');
INSERT INTO nombres VALUES(77,'aurelia','Latino','Dorado');
INSERT INTO nombres VALUES(78,'aurora','Latino','Amanecer');
INSERT INTO nombres VALUES(79,'auxiliadora','Latino','Que ayuda en situaciones difíciles');
INSERT INTO nombres VALUES(80,'axel','Germano','Recompensa del cielo');
INSERT INTO nombres VALUES(81,'azucena','Árabe','Lirio');
INSERT INTO nombres VALUES(82,'baldomero','Germano','Audaz, insigne');
INSERT INTO nombres VALUES(83,'baltasar','Caldeo','Dueño del tesoro');
INSERT INTO nombres VALUES(84,'barack','Africano','Beato, bendito');
INSERT INTO nombres VALUES(85,'bárbara','Griego','Extranjera');
INSERT INTO nombres VALUES(86,'bartolomé','Hebreo','Anciano');
INSERT INTO nombres VALUES(87,'basilio','Griego','Majestuosamente, regiamente');
INSERT INTO nombres VALUES(88,'bautista','Griego','Bautizador');
INSERT INTO nombres VALUES(89,'beatriz','Latino','Que hace feliz');
INSERT INTO nombres VALUES(90,'belén','Hebreo','Casa del pan');
INSERT INTO nombres VALUES(91,'belinda','Latino','Graciosa');
INSERT INTO nombres VALUES(92,'beltrán','Alemán','Audaz, insigne');
INSERT INTO nombres VALUES(93,'benigno','Latino','Bueno');
INSERT INTO nombres VALUES(94,'benito','Latino','Bendito');
INSERT INTO nombres VALUES(95,'benjamín','Hebreo','Hijo favorito (de la mano derecha)');
INSERT INTO nombres VALUES(96,'berenice','Griego','Ella da la victoria');
INSERT INTO nombres VALUES(97,'bernabé','Hebreo','Hijo de la profecía');
INSERT INTO nombres VALUES(98,'bernardino','','');
INSERT INTO nombres VALUES(99,'bernardina','Germano','Oso fuerte');
INSERT INTO nombres VALUES(100,'bernardo','Germano','Audaz como un oso');
INSERT INTO nombres VALUES(101,'berta','Germano','Brillante');
INSERT INTO nombres VALUES(102,'bianca','Germano','Blanca');
INSERT INTO nombres VALUES(103,'bibiana','Latino','Vital');
INSERT INTO nombres VALUES(104,'blanca','Germano','Pura, brillante');
INSERT INTO nombres VALUES(105,'blas','Griego','Tartamudo');
INSERT INTO nombres VALUES(106,'brenda','Anglosajón','Cuervo');
INSERT INTO nombres VALUES(107,'bonifacio','Latino','Bienhechor');
INSERT INTO nombres VALUES(108,'boris','Ruso','Pelea');
INSERT INTO nombres VALUES(109,'brígida','Celta','Fuerza');
INSERT INTO nombres VALUES(110,'brunilda','Germano','Doncella oscura de la batalla');
INSERT INTO nombres VALUES(111,'bruno','Germano','Oscuro');
INSERT INTO nombres VALUES(112,'calixto','Griego','De gran belleza');
INSERT INTO nombres VALUES(113,'camelia','Latino','Taza');
INSERT INTO nombres VALUES(114,'camila','Latino','La que espera el sacrificio');
INSERT INTO nombres VALUES(115,'cándido','Latino','Blanco');
INSERT INTO nombres VALUES(116,'caridad','Latino','Amor');
INSERT INTO nombres VALUES(117,'carina','Griego','Puro, inocente');
INSERT INTO nombres VALUES(118,'carlos','Germano','Fuerte, viril');
INSERT INTO nombres VALUES(119,'carla','Germano','Fuerte');
INSERT INTO nombres VALUES(120,'carolina','Germano','Fuerte');
INSERT INTO nombres VALUES(121,'carmelo','Hebreo','Viña');
INSERT INTO nombres VALUES(122,'carmen','Latino','Verso, cantar. Encantadora');
INSERT INTO nombres VALUES(123,'carol','Germano','Relativa a lo viril');
INSERT INTO nombres VALUES(124,'casilda','Árabe','Cantarina');
INSERT INTO nombres VALUES(125,'casimiro','Eslavo','Mira por la paz');
INSERT INTO nombres VALUES(126,'catalina','Griego','Pura');
INSERT INTO nombres VALUES(127,'cayetano','Latino','Natural de Gaeta (Itália)');
INSERT INTO nombres VALUES(128,'cecilia','Latino','Justa. Ciega (como la justicia)');
INSERT INTO nombres VALUES(129,'celestina','Latino','Celestial');
INSERT INTO nombres VALUES(130,'celia','Latino','Abreviatura de Celestina');
INSERT INTO nombres VALUES(131,'crisanto','Griego','Flor de oro');
INSERT INTO nombres VALUES(132,'cristián','Griego','Hombre de Cristo');
INSERT INTO nombres VALUES(133,'cristina','Latino','La que sigue a Cristo');
INSERT INTO nombres VALUES(134,'celso','Latino','Excelso');
INSERT INTO nombres VALUES(135,'césar','Latino','Adorno del cabello');
INSERT INTO nombres VALUES(136,'cesáreo','Latino','Nacido por cesárea');
INSERT INTO nombres VALUES(137,'cintia','Griego','Del lugar de Kinthos');
INSERT INTO nombres VALUES(138,'cipriano','Latino','Delgado, transparente');
INSERT INTO nombres VALUES(139,'cirilo','Griego','Señorial');
INSERT INTO nombres VALUES(140,'ciro','Persa','El sol');
INSERT INTO nombres VALUES(141,'clara','Latino','Brillante, ilustrada');
INSERT INTO nombres VALUES(142,'claudio claudia','Latino','Cojo');
INSERT INTO nombres VALUES(143,'clemente','Latino','Misericordioso, suave');
INSERT INTO nombres VALUES(144,'cleopatra','Griego','Gloria de su tierra');
INSERT INTO nombres VALUES(145,'clodoaldo','Latino','Fama,gloria.');
INSERT INTO nombres VALUES(146,'clotilde','Germano','Famosa en la batalla');
INSERT INTO nombres VALUES(147,'concepción','Latino','Que concibe');
INSERT INTO nombres VALUES(148,'conrado','Germano','Audaz, consejero, sabio');
INSERT INTO nombres VALUES(149,'constancio','Latino','Firme. Fidedigno');
INSERT INTO nombres VALUES(150,'constantino','Latino','Firme');
INSERT INTO nombres VALUES(151,'consuelo','Latino','Advertencia');
INSERT INTO nombres VALUES(152,'cora','Griego','Doncella');
INSERT INTO nombres VALUES(153,'cordelia','Celta','Joya del mar');
INSERT INTO nombres VALUES(154,'cornelio','Latino','Coronado');
INSERT INTO nombres VALUES(155,'cosme','Griego','Adornado');
INSERT INTO nombres VALUES(156,'cristóbal','Griego','Que lleva a Cristo');
INSERT INTO nombres VALUES(157,'crisóstomo','Griego','Boca de oro');
INSERT INTO nombres VALUES(158,'cruz','Latino','Cruz');
INSERT INTO nombres VALUES(159,'dagoberto','Germano','El que lleva la espada');
INSERT INTO nombres VALUES(160,'dana','Hebreo','Justicia');
INSERT INTO nombres VALUES(161,'daniel','Hebreo','Dios es juez');
INSERT INTO nombres VALUES(162,'darío','Persa','Preservador');
INSERT INTO nombres VALUES(163,'david','Hebreo','Amado');
INSERT INTO nombres VALUES(164,'débora','Hebreo','Abeja, industriosa');
INSERT INTO nombres VALUES(165,'delia','Griego','Casta');
INSERT INTO nombres VALUES(166,'delmiro','Germano','De nobleza insigne');
INSERT INTO nombres VALUES(167,'demetrio','Griego','Sagrado para la tierra');
INSERT INTO nombres VALUES(168,'diana','Latino','Diosa de la Luna');
INSERT INTO nombres VALUES(169,'diego','Hebreo','Suplantador');
INSERT INTO nombres VALUES(170,'dina','Hebreo','Vengada');
INSERT INTO nombres VALUES(171,'dionisio','Griego','Que pertenece a Dionisos (Baco)');
INSERT INTO nombres VALUES(172,'dolores','Latino','Pesares');
INSERT INTO nombres VALUES(173,'domingo dominico','Latino','Hijo del Señor');
INSERT INTO nombres VALUES(174,'donato','Latino','Regalo de Dios');
INSERT INTO nombres VALUES(175,'dora','Griego','Regalo de Dios');
INSERT INTO nombres VALUES(176,'dulcinea','Latino','Dulce');
INSERT INTO nombres VALUES(177,'edgardo','Germano','Justo, protector');
INSERT INTO nombres VALUES(178,'edith','Germano','Rico don');
INSERT INTO nombres VALUES(179,'edmundo','Germano','Paz bendita');
INSERT INTO nombres VALUES(180,'eduardo','Germano','Guardián de las mercancías');
INSERT INTO nombres VALUES(181,'efraín','Hebreo','Fructífero');
INSERT INTO nombres VALUES(182,'efrén','Hebreo','Fructífero');
INSERT INTO nombres VALUES(183,'elena eleonor','Griego','Luz');
INSERT INTO nombres VALUES(184,'elías','Hebreo','El Señor es Dios');
INSERT INTO nombres VALUES(185,'elisa','Hebreo','Dios del Juramento');
INSERT INTO nombres VALUES(186,'elisabeth','Hebreo','Consagrada a Dios');
INSERT INTO nombres VALUES(187,'eloisa','Germano','combatiente gloriosa');
INSERT INTO nombres VALUES(188,'eloy','Francés','Elegido');
INSERT INTO nombres VALUES(189,'elsa','Germano','Regocijo');
INSERT INTO nombres VALUES(190,'elvira','Latino','Noble, bravía');
INSERT INTO nombres VALUES(191,'emilia emilio','Griego','Graciosa/o');
INSERT INTO nombres VALUES(192,'ema','Griego','Que tiene gracia');
INSERT INTO nombres VALUES(193,'emanuel','Hebreo','Dios con nosotros');
INSERT INTO nombres VALUES(194,'emilio','Griego','Amable');
INSERT INTO nombres VALUES(195,'encarnación','Latino','Hacerse carne');
INSERT INTO nombres VALUES(196,'engracia','Latino','Favorecida por Dios');
INSERT INTO nombres VALUES(197,'enrique','Germano','Poderoso por su linaje');
INSERT INTO nombres VALUES(198,'erasmo','Griego','Que merece amor');
INSERT INTO nombres VALUES(199,'erico eric erica','Germano','Heroico');
INSERT INTO nombres VALUES(200,'ernesto','Germano','Serio. Celoso');
INSERT INTO nombres VALUES(201,'esmeralda','Latino','La muy admirada');
INSERT INTO nombres VALUES(202,'esperanza','Latino','Deseo');
INSERT INTO nombres VALUES(203,'esteban','Griego','Merecidamente coronado');
INSERT INTO nombres VALUES(204,'estefanía','Griego','Merecidamente coronada');
INSERT INTO nombres VALUES(205,'estela','Latín','Estrella');
INSERT INTO nombres VALUES(206,'ester','Persa','Estrella buena fortuna');
INSERT INTO nombres VALUES(207,'etel','Germano','Noble');
INSERT INTO nombres VALUES(208,'euclides','Griego','De buena reputación');
INSERT INTO nombres VALUES(209,'eudosia eudoxio eudo','Griego','Del/la que bien se piensa');
INSERT INTO nombres VALUES(210,'eufemio eufemia','Griego','De buena palabra');
INSERT INTO nombres VALUES(211,'eufrasio eufrasia','Griego','Regocijante');
INSERT INTO nombres VALUES(212,'eugenio eugenia','Griego','Bien nacido');
INSERT INTO nombres VALUES(213,'eulalio eulalia','Griego','Bien hablado');
INSERT INTO nombres VALUES(214,'eusebio','Griego','Piadoso');
INSERT INTO nombres VALUES(215,'eustaquio','Griego','Sano, firme');
INSERT INTO nombres VALUES(216,'eva','Hebreo','Vida');
INSERT INTO nombres VALUES(217,'evangelina','Griego','Que trae buenas nuevas');
INSERT INTO nombres VALUES(218,'evaristo','Griego','Óptimo');
INSERT INTO nombres VALUES(219,'ezequiel','Hebreo','El Señor es mi fuerza');
INSERT INTO nombres VALUES(220,'fabián','Latino','Granjero');
INSERT INTO nombres VALUES(221,'fabiola','Latino','Cultivadora de habas');
INSERT INTO nombres VALUES(222,'fanny','Germano','Libre');
INSERT INTO nombres VALUES(223,'fátima','Árabe','Doncella, joven');
INSERT INTO nombres VALUES(224,'faustino fausto','Latino','Afortunado');
INSERT INTO nombres VALUES(225,'federico','Germano','Que gobierna en paz');
INSERT INTO nombres VALUES(226,'fedor','Griego','Don de Dios');
INSERT INTO nombres VALUES(227,'félix','Latino','Feliz');
INSERT INTO nombres VALUES(228,'felipe','Griego','Amante de los caballos');
INSERT INTO nombres VALUES(229,'fermín','Latino','Fuerte y firme');
INSERT INTO nombres VALUES(230,'fernando','Germano','Valiente pero pacífico');
INSERT INTO nombres VALUES(231,'fidel','Latino','Fiel');
INSERT INTO nombres VALUES(232,'filiberto','Griego','Inteligente');
INSERT INTO nombres VALUES(233,'filomeno','Griego','Amante del canto');
INSERT INTO nombres VALUES(234,'flavio','Latino','De cabellos rubios');
INSERT INTO nombres VALUES(235,'flora','Latino','Flor, Diosa de las flores');
INSERT INTO nombres VALUES(236,'florencio florencia','Latino','Florido/a');
INSERT INTO nombres VALUES(237,'florida','Latino','Colorida');
INSERT INTO nombres VALUES(238,'florinda','Latino','Colorida');
INSERT INTO nombres VALUES(239,'florián','Latino','Floreciente, próspero');
INSERT INTO nombres VALUES(240,'francisco','Germano','Libre');
INSERT INTO nombres VALUES(241,'franco','Germano','Libre');
INSERT INTO nombres VALUES(242,'frida','Germano','Pacífica');
INSERT INTO nombres VALUES(243,'froilán','Germano','Compañero');
INSERT INTO nombres VALUES(244,'fulvio','Latino','Dorado');
INSERT INTO nombres VALUES(245,'gabriel','Hebreo','Fuerza de Dios');
INSERT INTO nombres VALUES(246,'galatea','Griego','Blanca como la leche');
INSERT INTO nombres VALUES(247,'gaspar','Persa','Tesorero');
INSERT INTO nombres VALUES(248,'gedeón','Hebreo','De la colina');
INSERT INTO nombres VALUES(249,'genoveva','Celta','Espuma de mar');
INSERT INTO nombres VALUES(250,'gerardo','Germano','Hábil en armas');
INSERT INTO nombres VALUES(251,'germán','Latino','Alemán');
INSERT INTO nombres VALUES(252,'gertrudis','Germano','Veraz');
INSERT INTO nombres VALUES(253,'gilberto','Germano','Sirviente brillante');
INSERT INTO nombres VALUES(254,'gladis','Celta','Que gobierna un gran territorio');
INSERT INTO nombres VALUES(255,'gloria','Latino','Fama');
INSERT INTO nombres VALUES(256,'godofredo','Germano','Paz de Dios');
INSERT INTO nombres VALUES(257,'gracia','Latino','Gracia');
INSERT INTO nombres VALUES(258,'graciela','Latino','Agraciada');
INSERT INTO nombres VALUES(259,'gregorio','Griego','Vigilante');
INSERT INTO nombres VALUES(260,'grisel','Germano','De ojos grises');
INSERT INTO nombres VALUES(261,'griselda','Germano','De ojos grises');
INSERT INTO nombres VALUES(262,'gualterio','Germano','Guerrero poderoso');
INSERT INTO nombres VALUES(263,'guido','Latino','Guía, conductor');
INSERT INTO nombres VALUES(264,'guillermo','Germano','Casco de oro');
INSERT INTO nombres VALUES(265,'gustavo','Germano','Báculo del godo');
INSERT INTO nombres VALUES(266,'haroldo','Germano','General');
INSERT INTO nombres VALUES(267,'haydee','Griego','Acariciada');
INSERT INTO nombres VALUES(268,'hebe','Griego','Juventud');
INSERT INTO nombres VALUES(269,'helena','Griego','Antorcha');
INSERT INTO nombres VALUES(270,'heli','Hebreo','De Dios');
INSERT INTO nombres VALUES(271,'héctor','Griego','Prudente defensor');
INSERT INTO nombres VALUES(272,'heriberto heriberta','Germano','De ejército distinguido');
INSERT INTO nombres VALUES(273,'hermelando hermelind','Germano','De antigua tribu germánica');
INSERT INTO nombres VALUES(274,'herminio herminia','Germano','Enérgica');
INSERT INTO nombres VALUES(275,'hernán','Germano','Atrevido, bravo');
INSERT INTO nombres VALUES(276,'higinio higinia','Griego','Vigoroso');
INSERT INTO nombres VALUES(277,'hilario hilaria','Latino','Alegre, risueño');
INSERT INTO nombres VALUES(278,'hilda','Germano','Poderosa en la batalla');
INSERT INTO nombres VALUES(279,'hipólito','Griego','Caballo de piedra');
INSERT INTO nombres VALUES(280,'homero','Griego','Prenda, fianza, rehén');
INSERT INTO nombres VALUES(281,'honorio','Latino','Honorable');
INSERT INTO nombres VALUES(282,'horacio','Latino','De mirada penetrante');
INSERT INTO nombres VALUES(283,'hortensio','Latino','Jardinero');
INSERT INTO nombres VALUES(284,'hugo','Germano','Altivo, inteligente');
INSERT INTO nombres VALUES(285,'huberto','Germano','Inteligencia luminosa');
INSERT INTO nombres VALUES(286,'humberto','Germano','Muy brillante');
INSERT INTO nombres VALUES(287,'ida','Griego','Feliz');
INSERT INTO nombres VALUES(288,'idefonso','Germano','Luchador');
INSERT INTO nombres VALUES(289,'ignacio','Griego','Orgulloso');
INSERT INTO nombres VALUES(290,'imanol','Vasco','Forma de Manuel y Emanuel (hebreo). Dios con nosotros');
INSERT INTO nombres VALUES(291,'imelda','Germano','Poderosa en la lucha');
INSERT INTO nombres VALUES(292,'iñigo','Griego','Orgulloso');
INSERT INTO nombres VALUES(293,'indalecio','Vasco','Fuerza');
INSERT INTO nombres VALUES(294,'inés','Griego','Pura, casta');
INSERT INTO nombres VALUES(295,'ingrid','Germano','De la tribu de los ingviones');
INSERT INTO nombres VALUES(296,'irene','Griego','Paz');
INSERT INTO nombres VALUES(297,'iris','Griego','Arco Iris');
INSERT INTO nombres VALUES(298,'irma','Germano','Noble doncella');
INSERT INTO nombres VALUES(299,'isaac','Hebreo','El que ríe');
INSERT INTO nombres VALUES(300,'isabel','Hebreo','Dios del Juramento');
INSERT INTO nombres VALUES(301,'isadora isidoro','Griego','Don equitativo');
INSERT INTO nombres VALUES(302,'isaías','Hebreo','Salvación del Señor');
INSERT INTO nombres VALUES(303,'israel','Hebreo','Príncipe de Dios');
INSERT INTO nombres VALUES(304,'iván','Hebreo','Dios es misericordioso');
INSERT INTO nombres VALUES(305,'ivana','Hebreo','Dios es misericordioso');
INSERT INTO nombres VALUES(306,'ivonne','Germano','Gloriosa');
INSERT INTO nombres VALUES(307,'jacinto','Griego','Flor');
INSERT INTO nombres VALUES(308,'jacobo','Hebreo','Suplantador');
INSERT INTO nombres VALUES(309,'jaqueline','Francés','Que se agarra el talón');
INSERT INTO nombres VALUES(310,'jairo','Hebreo','Dios quiera lucir');
INSERT INTO nombres VALUES(311,'javier','Vasco','Casa nueva');
INSERT INTO nombres VALUES(312,'jazmín','Persa','Flor del mismo nombre');
INSERT INTO nombres VALUES(313,'jaime','Hebreo','Suplantador');
INSERT INTO nombres VALUES(314,'jennifer','Galés','Blanca como la espuma de mar');
INSERT INTO nombres VALUES(315,'jeremías','Hebreo','Elevado por el Señor- Exaltación del Señor');
INSERT INTO nombres VALUES(316,'jerónimo','Griego','Sagrado');
INSERT INTO nombres VALUES(317,'jessica','Escocés','Forma escocesa de Juana');
INSERT INTO nombres VALUES(318,'jesús','Hebreo','Diminutivo de Jehová');
INSERT INTO nombres VALUES(319,'joaquín','Hebreo','El Señor juzgará');
INSERT INTO nombres VALUES(320,'job','Hebreo','Perseguido');
INSERT INTO nombres VALUES(321,'jonatan jonhatan','Hebreo','Don de Dios');
INSERT INTO nombres VALUES(322,'jorge','Griego','Agricultor');
INSERT INTO nombres VALUES(323,'josé','Hebreo','Aumentará (hijos)');
INSERT INTO nombres VALUES(324,'josefa','Hebreo','Dios proveerá (hijos)');
INSERT INTO nombres VALUES(325,'josefina','Hebreo','Dios dará');
INSERT INTO nombres VALUES(326,'jonás','Hebreo','Paloma');
INSERT INTO nombres VALUES(327,'josué','Hebreo','El Señor es la salvación');
INSERT INTO nombres VALUES(328,'juan','Latino','Don gracioso de Dios');
INSERT INTO nombres VALUES(329,'juana','Latino','Don de Dios');
INSERT INTO nombres VALUES(330,'judá','Hebreo','Alabado');
INSERT INTO nombres VALUES(331,'judit judith','Hebreo','Alabada');
INSERT INTO nombres VALUES(332,'julia','Latino','De cabello suave');
INSERT INTO nombres VALUES(333,'juliana','Latino','De cabello suave');
INSERT INTO nombres VALUES(334,'julio julián','Latino','De mucho pelo. Barbudo');
INSERT INTO nombres VALUES(335,'justiniano justo','Latino','Recto');
INSERT INTO nombres VALUES(336,'karen','Danés','Pura, inmaculada (del griego Catalina)');
INSERT INTO nombres VALUES(337,'katia','Ruso','Pura, inmaculada (del griego Catalina)');
INSERT INTO nombres VALUES(338,'kevin','Irlandés','Bonito nacimiento');
INSERT INTO nombres VALUES(339,'lamberto','Germano','Oveja bravía');
INSERT INTO nombres VALUES(340,'laura','Latino','Laurel (signo del triunfo)');
INSERT INTO nombres VALUES(341,'lázaro','Hebreo','Ayuda de Dios');
INSERT INTO nombres VALUES(342,'leandro','Griego','Célebre');
INSERT INTO nombres VALUES(343,'león','Latino','León');
INSERT INTO nombres VALUES(344,'leonardo','Germano','Fuerte como un león');
INSERT INTO nombres VALUES(345,'leónidas','Griego','Como el león');
INSERT INTO nombres VALUES(346,'leonor leonora','Griego','Luz');
INSERT INTO nombres VALUES(347,'leopoldo','Germano','Príncipe del pueblo, fuerte y amado');
INSERT INTO nombres VALUES(348,'leticia','Latino','Felicidad');
INSERT INTO nombres VALUES(349,'lía','Hebreo','Lánguida');
INSERT INTO nombres VALUES(350,'lida','Eslavo','Amada del pueblo');
INSERT INTO nombres VALUES(351,'lidia lydia','Griego','Nacido en Lydia (Asia Menor)');
INSERT INTO nombres VALUES(352,'liliana','Latino','Lirio (símbolo de pureza)');
INSERT INTO nombres VALUES(353,'lina','Germano','Diminutivo de Carola - Fuerte');
INSERT INTO nombres VALUES(354,'linda','Latino','Graciosa');
INSERT INTO nombres VALUES(355,'lorenzo','Latino','Coronado de laurel');
INSERT INTO nombres VALUES(356,'lucas','Griego','Luminoso (forma griega de Lucio)');
INSERT INTO nombres VALUES(357,'lucía','Latino','Luminoso');
INSERT INTO nombres VALUES(358,'luciano lucio','Latino','Luminoso');
INSERT INTO nombres VALUES(359,'lucrecia','Latino','Afortunada');
INSERT INTO nombres VALUES(360,'luis','Germano','Defensor del pueblo');
INSERT INTO nombres VALUES(361,'mabel','Celta','Alegre');
INSERT INTO nombres VALUES(362,'macarena','Sevillano','Alusivo al barrio del mismo nombre');
INSERT INTO nombres VALUES(363,'magalí','Provenzal','Perla');
INSERT INTO nombres VALUES(364,'magdalena','Hebreo','Torre, vigilante');
INSERT INTO nombres VALUES(365,'maite','Vasco','Encarnación');
INSERT INTO nombres VALUES(366,'malvina','Celta','Criada');
INSERT INTO nombres VALUES(367,'manuel','Hebreo','Dios con nosotros');
INSERT INTO nombres VALUES(368,'marcelo','Latino','Guerrero');
INSERT INTO nombres VALUES(369,'marcos','Hebreo','Amargo');
INSERT INTO nombres VALUES(370,'margarita','Griego','Perla');
INSERT INTO nombres VALUES(371,'maría','Hebreo','Señora');
INSERT INTO nombres VALUES(372,'mariana','Hebreo','Señor en la gracia de Dios');
INSERT INTO nombres VALUES(373,'marta','Hebreo','Afligida');
INSERT INTO nombres VALUES(374,'martín','Latino','Guerrero');
INSERT INTO nombres VALUES(375,'mateo matías','Hebreo','Don del Señor');
INSERT INTO nombres VALUES(376,'matilde','Germano','Poderosa en la batalla');
INSERT INTO nombres VALUES(377,'mauricio mauro','Latino','Moro, de color oscuro');
INSERT INTO nombres VALUES(378,'máximiliano máximo','Latino','De los más grandes');
INSERT INTO nombres VALUES(379,'miguel','Hebreo','¿Quién es como Dios?');
INSERT INTO nombres VALUES(380,'mina','Latino','Pequeña');
INSERT INTO nombres VALUES(381,'miriam','Hebreo','Rebelión');
INSERT INTO nombres VALUES(382,'mirta','Griego','Mirto (Símbolo de la belleza)');
INSERT INTO nombres VALUES(383,'moisés','Hebreo','Salvado de las aguas');
INSERT INTO nombres VALUES(384,'mónica','Griego','Solitaria');
INSERT INTO nombres VALUES(385,'napoleón','Griego','León de la nueva ciudad');
INSERT INTO nombres VALUES(386,'narciso','Griego','Hermoso');
INSERT INTO nombres VALUES(387,'natalio','Latino','Recién nacido');
INSERT INTO nombres VALUES(388,'natán','Hebreo','Don de Dios');
INSERT INTO nombres VALUES(389,'naúm','Hebreo','Confortador');
INSERT INTO nombres VALUES(390,'nélida','Griego','Luz (variante de Elena)');
INSERT INTO nombres VALUES(391,'néstor','Griego','El que recuerda');
INSERT INTO nombres VALUES(392,'nicolás','Griego','Conquistador');
INSERT INTO nombres VALUES(393,'nidia','Latino','Ave recién salida del nido');
INSERT INTO nombres VALUES(394,'noé','Hebreo','Descanso');
INSERT INTO nombres VALUES(395,'norma','Latino','Modelo, regla');
INSERT INTO nombres VALUES(396,'nuria','Latino','Advocación catalana a la Virgen María');
INSERT INTO nombres VALUES(397,'obama','Africano','Ligeramente dobladas');
INSERT INTO nombres VALUES(398,'octavio','Latino','Octavo');
INSERT INTO nombres VALUES(399,'ofelia','Griego','Serpiente');
INSERT INTO nombres VALUES(400,'olga','Germano','Sagrada');
INSERT INTO nombres VALUES(401,'olimpia','Griego','Celestial');
INSERT INTO nombres VALUES(402,'oliverio','Latino','El que porta la rama de olivo');
INSERT INTO nombres VALUES(403,'olivia','Latino','El olivo (signo de paz)');
INSERT INTO nombres VALUES(404,'omar','Árabe','Mejor');
INSERT INTO nombres VALUES(405,'orlando','Italiano','Fama del país (Forma italiana de Rolando)');
INSERT INTO nombres VALUES(406,'oscar','Celta','Guerrero saltarín');
INSERT INTO nombres VALUES(407,'osvaldo','Germano','Regidor divino');
INSERT INTO nombres VALUES(408,'otón','Germano','Montaña');
INSERT INTO nombres VALUES(409,'pablo paolo','Latino','Pequeño');
INSERT INTO nombres VALUES(410,'pánfilo','Griego','Amigo de todos');
INSERT INTO nombres VALUES(411,'paloma','Latino','Paloma');
INSERT INTO nombres VALUES(412,'pascual','Latino','De las Pascuas');
INSERT INTO nombres VALUES(413,'patricio','Latino','Noble');
INSERT INTO nombres VALUES(414,'paula paola','Latino','Pequeña');
INSERT INTO nombres VALUES(415,'paulino','Griego','El más pequeño');
INSERT INTO nombres VALUES(416,'paulina','Griego','La más pequeña');
INSERT INTO nombres VALUES(417,'paz','Latino','Se usa especialmente como advocación mariana');
INSERT INTO nombres VALUES(418,'pedro','Griego','Roca');
INSERT INTO nombres VALUES(419,'penélope','Griego','Aumenta lo tejido');
INSERT INTO nombres VALUES(420,'perla','Latino','Perla (Símbolo de salud)');
INSERT INTO nombres VALUES(421,'pilar','Latino','Alta, fuerte');
INSERT INTO nombres VALUES(422,'piedad','Latino','Devoción');
INSERT INTO nombres VALUES(423,'pío pía','Latino','Devoto/a');
INSERT INTO nombres VALUES(424,'priscila','Latino','Antigua, venerable');
INSERT INTO nombres VALUES(425,'prudencia','Latino','Prudencia (virtud de ser prudente)');
INSERT INTO nombres VALUES(426,'pura','Latino','Sin mancha');
INSERT INTO nombres VALUES(427,'rafael','Hebreo','Dios ha curado');
INSERT INTO nombres VALUES(428,'raimundo','Germano','Protección sabia');
INSERT INTO nombres VALUES(429,'ramiro','Germano','Poderoso en la guerra');
INSERT INTO nombres VALUES(430,'ramona','Germano','Protectora sensata');
INSERT INTO nombres VALUES(431,'ramón','Germano','Protector sensato');
INSERT INTO nombres VALUES(432,'raquel','Hebreo','Oveja del Señor');
INSERT INTO nombres VALUES(433,'raúl','Francés','Guerrero atrevido');
INSERT INTO nombres VALUES(434,'rebeca','Hebreo','Lazo corredizo, trampa');
INSERT INTO nombres VALUES(435,'reina','Latino','Reina');
INSERT INTO nombres VALUES(436,'reinaldo','Germano','Juez poderoso');
INSERT INTO nombres VALUES(437,'regina','Latino','Reina');
INSERT INTO nombres VALUES(438,'remedios','Latino','Alivio');
INSERT INTO nombres VALUES(439,'renato','Latino','Renacido');
INSERT INTO nombres VALUES(440,'rené','Latino','Renacido');
INSERT INTO nombres VALUES(441,'ricardo','Germano','Guerrero temerario');
INSERT INTO nombres VALUES(442,'rita','Latino','Ceremoniosa');
INSERT INTO nombres VALUES(443,'roberto','Germano','De fama brillante');
INSERT INTO nombres VALUES(444,'rocío','Latino','Lágrimas de flor');
INSERT INTO nombres VALUES(445,'rodolfo','Germano','Lobo de fama');
INSERT INTO nombres VALUES(446,'rodrigo','Germano','Rico en fama');
INSERT INTO nombres VALUES(447,'rogelio','Germano','Lanza de fama');
INSERT INTO nombres VALUES(448,'rolando rolán','Germano','Fama del país');
INSERT INTO nombres VALUES(449,'román','Latino','De Rumania');
INSERT INTO nombres VALUES(450,'romeo','Latino','Buen hombre de Roma');
INSERT INTO nombres VALUES(451,'romilda','Germano','Guerrera famosa');
INSERT INTO nombres VALUES(452,'romildo','Germano','Guerrero famoso');
INSERT INTO nombres VALUES(453,'ronaldo','Germano','Gobernante glorioso');
INSERT INTO nombres VALUES(454,'roque','Persa','Elevado');
INSERT INTO nombres VALUES(455,'rosa','Latino','La rosa');
INSERT INTO nombres VALUES(456,'rosalía','Latino','Rosa pequeña');
INSERT INTO nombres VALUES(457,'rosamunda','Germano','Guardia famosa');
INSERT INTO nombres VALUES(458,'rosana','Latino','Como una rosa');
INSERT INTO nombres VALUES(459,'rosario','Latino','Jardín de rosas');
INSERT INTO nombres VALUES(460,'rosendo','Germano','Soldado');
INSERT INTO nombres VALUES(461,'roxana','Persa','La brillante');
INSERT INTO nombres VALUES(462,'rubén','Hebreo','¡He aquí un hijo!');
INSERT INTO nombres VALUES(463,'rufino','Latino','Rojo');
INSERT INTO nombres VALUES(464,'ruperto','Germano','De fama brillante');
INSERT INTO nombres VALUES(465,'rut ruth','Hebreo','Amistad, misericordia');
INSERT INTO nombres VALUES(466,'sabina','Latino','Mujer sabina (El pueblo de Italia)');
INSERT INTO nombres VALUES(467,'sagrario','Latino','Receptáculo sagrado');
INSERT INTO nombres VALUES(468,'salomé','Hebreo','Pacífica');
INSERT INTO nombres VALUES(469,'salomón','Hebreo','Pacífico');
INSERT INTO nombres VALUES(470,'salvador','Latino','Salvador');
INSERT INTO nombres VALUES(471,'samanta','Hebreo','Que escucha');
INSERT INTO nombres VALUES(472,'samuel','Hebreo','Oído por Dios');
INSERT INTO nombres VALUES(473,'sancho','Latino','Santo');
INSERT INTO nombres VALUES(474,'sandra','Germano','Auxiliar de los hombres');
INSERT INTO nombres VALUES(475,'sansón','Hebreo','Como el sol');
INSERT INTO nombres VALUES(476,'santiago','Latino','Sancti Yago (Del hebreo Jacobo: Suplantador)');
INSERT INTO nombres VALUES(477,'sara','Hebreo','Princesa');
INSERT INTO nombres VALUES(478,'saúl','Hebreo','Llamado');
INSERT INTO nombres VALUES(479,'sebastián','Griego','Venerable, augusto');
INSERT INTO nombres VALUES(480,'segismundo','Germano','Vencedor');
INSERT INTO nombres VALUES(481,'serafín','Hebreo','Ángel de fuego');
INSERT INTO nombres VALUES(482,'serena','Latino','Tranquila');
INSERT INTO nombres VALUES(483,'sergio','Latino','De Serbia');
INSERT INTO nombres VALUES(484,'sigfrido','Germano','Conquistador de la paz');
INSERT INTO nombres VALUES(485,'servando','Latino','Observa, cumple, guarda');
INSERT INTO nombres VALUES(486,'sheila','Irlandés','Celestial. Antigua adaptación de Celia');
INSERT INTO nombres VALUES(487,'silván silvano','Latino','Del bosque');
INSERT INTO nombres VALUES(488,'silvestre','Latino','Rústico');
INSERT INTO nombres VALUES(489,'silvio silvia','Latino','Del bosque');
INSERT INTO nombres VALUES(490,'simón simeón','Hebreo','El que escucha');
INSERT INTO nombres VALUES(491,'siro','Persa','Sol');
INSERT INTO nombres VALUES(492,'sixto','Griego','Adulador');
INSERT INTO nombres VALUES(493,'socorro','Latino','Dispuesta a ayudar');
INSERT INTO nombres VALUES(494,'sofía','Griego','Sabiduría');
INSERT INTO nombres VALUES(495,'sol','Latino','Astro rey');
INSERT INTO nombres VALUES(496,'solange','Francés','Solemne');
INSERT INTO nombres VALUES(497,'soledad','Latino','Sin compañía');
INSERT INTO nombres VALUES(498,'soraya','Persa','Excelente');
INSERT INTO nombres VALUES(499,'sonia','Griego','Sabia pensadora');
INSERT INTO nombres VALUES(500,'susana','Hebreo','Lirio');
INSERT INTO nombres VALUES(501,'suyay','Quechua','Esperar, aguardar');
INSERT INTO nombres VALUES(502,'tadeo','Hebreo','Oración de gracias');
INSERT INTO nombres VALUES(503,'tamar  tamara','Hebreo','Palmera');
INSERT INTO nombres VALUES(504,'tania','Ruso','Que procede de Tacio, legendario rey de los sabinos');
INSERT INTO nombres VALUES(505,'tatiana','Latino','Defensora');
INSERT INTO nombres VALUES(506,'telma','Griego','Favorita, niña mimada');
INSERT INTO nombres VALUES(507,'teobaldo','Germano','Príncipe del pueblo');
INSERT INTO nombres VALUES(508,'teodoro','Griego','Don de Dios');
INSERT INTO nombres VALUES(509,'teodorico','Germano','Regla del pueblo');
INSERT INTO nombres VALUES(510,'teodosio','Griego','Dado divinamente');
INSERT INTO nombres VALUES(511,'teófilo','Griego','Amante de Dios');
INSERT INTO nombres VALUES(512,'teresa','Griego','Que lleva espigas de trigo');
INSERT INTO nombres VALUES(513,'tirso','Latino','Rama de vid');
INSERT INTO nombres VALUES(514,'tito','Latino','Defensor');
INSERT INTO nombres VALUES(515,'timoteo','Griego','Que honra a Dios');
INSERT INTO nombres VALUES(516,'tobías','Hebreo','El Señor es bueno');
INSERT INTO nombres VALUES(517,'tomás','Hebreo','Mellizo, gemelo');
INSERT INTO nombres VALUES(518,'trinidad','Latino','Tres en uno');
INSERT INTO nombres VALUES(519,'tristán','Escocés','Pacto, consuelo');
INSERT INTO nombres VALUES(520,'ulises','Griego','Colérico, iracundo');
INSERT INTO nombres VALUES(521,'ulrico','Germano','Noble señor');
INSERT INTO nombres VALUES(522,'urbano','Latino','Dios del hogar');
INSERT INTO nombres VALUES(523,'uriel','Hebreo','Luz de Dios');
INSERT INTO nombres VALUES(524,'ursula','Latino','Osa pequeña');
INSERT INTO nombres VALUES(525,'valentín','Latino','Fuerte, valeroso');
INSERT INTO nombres VALUES(526,'valerio  valeria','Latino','Sano');
INSERT INTO nombres VALUES(527,'vanesa','Creado por Jonathan','Del personaje Esther Vanhomringh');
INSERT INTO nombres VALUES(528,'ventura','Latino','Afortunado');
INSERT INTO nombres VALUES(529,'velasco','Germano','Cuervo');
INSERT INTO nombres VALUES(530,'vera','Latino','Verdadera');
INSERT INTO nombres VALUES(531,'verónica','Latino','Imagen de la verdad');
INSERT INTO nombres VALUES(532,'vicente','Latino','Conquistador');
INSERT INTO nombres VALUES(533,'víctor  victoria  vi','Latino','Vencedor/a');
INSERT INTO nombres VALUES(534,'vida','Latino','Vacía');
INSERT INTO nombres VALUES(535,'vilma','Germano','Protectora');
INSERT INTO nombres VALUES(536,'violeta','Latino','Violeta (Símbolo de modestia)');
INSERT INTO nombres VALUES(537,'virgilio','Latino','Floreciente');
INSERT INTO nombres VALUES(538,'virginia','Latino','Virgen');
INSERT INTO nombres VALUES(539,'viviana','Latino','Vivaz, animada');
INSERT INTO nombres VALUES(540,'vladimir','Eslavo','Gloria del príncipe');
INSERT INTO nombres VALUES(541,'walter','Germano','Caudillo del Ejército');
INSERT INTO nombres VALUES(542,'wenceslao','Checo','El más glorioso');
INSERT INTO nombres VALUES(543,'wilfredo','Germano','Pacificador decidido');
INSERT INTO nombres VALUES(544,'xavier','Gallego','Casa nueva');
INSERT INTO nombres VALUES(545,'yago','','Igual a Jacobo');
INSERT INTO nombres VALUES(546,'yeray','Canario','Grande');
INSERT INTO nombres VALUES(547,'yolanda','Germano','La más justa');
INSERT INTO nombres VALUES(548,'zacarías','Hebreo','El Señor ha recordado');
INSERT INTO nombres VALUES(549,'zenobia','Árabe','Orgullo de su padre');
INSERT INTO nombres VALUES(550,'zoe','Griego','Vida');
INSERT INTO nombres VALUES(551,'zita','Toscano','Muchacha alegre');
INSERT INTO nombres VALUES(552,'zoraida','Árabe','Mujer cautivadora');
CREATE UNIQUE INDEX nombre ON nombres(nombre ASC);